name: Run test-suite

on:
  workflow_dispatch:
  pull_request:

jobs:
  check_settings:

    runs-on: ubuntu-latest
    name: Run test-suite

    steps:

    - uses: actions/checkout@v4
      with:
        lfs: 'true'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run test-suite
      working-directory: ./django
      run: python manage.py test
      env:
        CS2PB_ADMIN_MAIL_ADDRESS: ${{ vars.CS2PB_ADMIN_MAIL_ADDRESS }}
        CS2PB_STEAM_API_KEY: ${{ vars.CS2PB_STEAM_API_KEY }}
